#!/usr/bin/perl 

# 
# Script to manipulate data files for gnuplot
#

(@ARGV == 2) or die "2 parameters needed: fac1, fac2"; 

# string -> number missing, ex 1/120

($factor1, $factor2) = @ARGV;


$IN = "data.dat";
$OUT = ">data_mod.dat";


open IN or die "Datei $IN der Daten $! nicht gefunden\n";
open OUT or die "Die Datei $OUT kann nisht angelegt werden\n";

while (<IN>) {
	chop;
	if (/^#/) { 
		#
		# modify header and add scaling factors
		#
		print OUT $_."\n";
		print OUT "#\n";
		print OUT "# on ".`date`;
		print OUT "# modified by scale_data.pl\n";
		print OUT "# scaled by $factor1 and $factor2\n";
		print OUT "#\n";
	} else {
		#
		# scale values
		#
		($eins, $zwei) = split(/ /);
		print OUT $eins*$factor1." ".$zwei*$factor2."\n";
	}

}
close OUT;
close IN;
